server: 
  port: 8764
  servlet:
    context-path: /mobile
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    eureka-server-read-timeout-seconds: 30
spring:
    freemarker:
      suffix: .ftl
      charset: UTF-8
      templateLoaderPath: classpath:/templates/
    application:
      name: mobile